CI: humble ci

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -2,10 +2,10 @@ name: snap
 on:
   push:
     branches:
-      - noetic-devel
+      - humble-devel
   pull_request:
     branches:
-      - noetic-devel
+      - humble-devel
   workflow_dispatch:
   workflow_call:
    inputs:
@@ -16,130 +16,137 @@ on:
 
 jobs:
   snap:
-    uses: ubuntu-robotics/snap_workflows/.github/workflows/snap.yaml@main
+    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
     secrets:
-      store-login: ${{ secrets.STORE_LOGIN }}
+      snapstore-login: ${{ secrets.STORE_LOGIN }}
     with:
-      ubuntu-image: ubuntu-20.04
-      branch-name: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
-      snap-name: turtlebot3c
-      publish: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
-      test-script: |
-                    #!/bin/bash
+      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "large", "noble"]]'
+      lxd-image: "ubuntu:22.04"
+      snapcraft-source-subdir: "."
+      git-ref: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
+      snap-test-script: |
+            #!/bin/bash
 
-                    check_publishing() {
-                        local name=$1
-                        local timeout=$2
-                        local start_time=$(date +%s)
+            set -euxo pipefail
 
-                        while [ -z "${topic_data}" ]; do
-                          echo "waiting for /$name data"
-                          topic_data=$(rostopic echo -n 10 /$name 2>/dev/null)
-                          if [ -z "${topic_data}" ]; then
-                            echo "Topic /$name is not publishing data."
-                          else
-                            echo "Topic /$name is publishing data. Exiting."
-                          fi
+            export HOME=/home/ubuntu
 
-                          local current_time=$(date +%s)
-                          local elapsed_time=$((current_time - start_time))
-                          
-                          if [ $elapsed_time -ge $timeout ]; then
-                              echo "Error $name is not running."
-                              exit 1
-                          fi
-                          sleep 1
-                        done
-                    }
+            check_publishing() {
+                local name=$1
+                local timeout=$2
+                local start_time=$(date +%s)
+                local topic_data=""
 
-                    check_existence() {
-                        local topic_or_node=$1
-                        local name=$2
-                        local timeout=$3
-                        local start_time=$(date +%s)
+                while [ -z "${topic_data}" ]; do
+                  echo "waiting for /$name data"
+                  topic_data=$(rostopic echo -n 10 /$name 2>/dev/null)
+                  if [ -z "${topic_data}" ]; then
+                    echo "Topic /$name is not publishing data."
+                  else
+                    echo "Topic /$name is publishing data. Exiting."
+                  fi
 
-                        while true; do
-                            $topic_or_node list | grep -q "/$name"
-                            if [ $? -eq 0 ]; then
-                                echo "$name is running."
-                                return 0
-                            fi
+                  local current_time=$(date +%s)
+                  local elapsed_time=$((current_time - start_time))
 
-                            local current_time=$(date +%s)
-                            local elapsed_time=$((current_time - start_time))
+                  if [ $elapsed_time -ge $timeout ]; then
+                      echo "Error $name is not running."
+                      exit 1
+                  fi
+                  sleep 1
+                done
+            }
 
-                            if [ $elapsed_time -ge $timeout ]; then
-                                echo "Error $name is not running."
-                                sudo snap stop turtlebot3c
-                                exit 1
-                            fi
-                            sleep 1
-                        done
-                    }
+            check_existence() {
+                local topic_or_node=$1
+                local name=$2
+                local timeout=$3
+                local start_time=$(date +%s)
+                local error_code=0
 
-                    ## Install ROS
-                    sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
+                while true; do
+                    error_code=$($topic_or_node list | grep -q "/$name"; echo $?)
+                    if [ $error_code -eq 0 ]; then
+                        echo "$name is running."
+                        return 0
+                    fi
 
-                    sudo apt install curl
-                    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
-                    sudo apt update
-                    sudo apt install ros-noetic-desktop-full
-                    sudo apt install ros-noetic-turtlebot3-gazebo
+                    local current_time=$(date +%s)
+                    local elapsed_time=$((current_time - start_time))
 
-                    source /opt/ros/noetic/setup.sh
+                    if [ $elapsed_time -ge $timeout ]; then
+                        echo "Error $name is not running."
+                        sudo snap stop turtlebot3c
+                        exit 1
+                    fi
+                    sleep 1
+                done
+            }
 
-                    echo "Set the simulation parameter"
-                    sudo snap set turtlebot3c simulation=true
-                    sleep 10
+            ## Install ROS
+            echo "Installing ROS"
+            sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros2.list'
 
-                    ## set gui arg to false with sed since the arg is not exposed
-                    sudo sed -i "s/\(<arg name=\"gui\" value=\"\).*\(\"\/>\)/\1false\2/" /opt/ros/noetic/share/turtlebot3_gazebo/launch/turtlebot3_empty_world.launch
+            sudo apt install --yes curl
+            curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
+            sudo apt -q update
+            sudo apt install -q --yes ros-humble-desktop-full
+            sudo apt install -q --yes ros-humble-turtlebot3-gazebo
 
-                    ## Launch turtlebot simulation
-                    TURTLEBOT3_MODEL=waffle_pi roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch &
-                    pid=$!
+            set +u
+            source /opt/ros/humble/setup.bash
+            set -u
 
-                    echo "check simulation is running"
-                    check_publishing scan 30
-                    check_publishing joint_states 30
+            echo "Set the simulation parameter"
+            sudo snap set turtlebot3c simulation=true
+            sleep 10
 
-                    ## test core robot_state_publisher
-                    check_existence rostopic tf 30
-                    check_existence rosnode robot_state_publisher 30
+            ## set gui arg to false with sed since the arg is not exposed
+            sudo sed -i "s/\(<arg name=\"gui\" value=\"\).*\(\"\/>\)/\1false\2/" /opt/ros/humble/share/turtlebot3_gazebo/launch/turtlebot3_empty_world.launch
 
-                    ## test mapping node
-                    sudo snap start turtlebot3c.mapping
-                    check_existence rosnode turtlebot3_slam_gmapping 30
-                    check_existence rostopic map 30
-                    echo "moving the robot"
-                    timeout 5s rostopic pub -r 10 /cmd_vel geometry_msgs/Twist -- '[0.0, 0.0, 0.0]' '[1.0, 0.0, 0.0]'
-                    check_publishing map 30
-                    sudo snap stop turtlebot3c.mapping
-                    
-                    ## check map has been created
-                    timeout=30
-                    start_time=$(date +%s)
-                    while true; do
-                        echo "check map exists.."
-                        sudo bash -c 'cd /root/snap/turtlebot3c/common/map/ && ls | grep -q "current_map.yaml"'
-                        if [ $? -eq 0 ]; then
-                          echo "map found - starting navigation"
-                          break
-                        fi
-                        current_time=$(date +%s)
-                        elapsed_time=$((current_time - start_time))
-                        if [ $elapsed_time -ge $timeout ]; then
-                            echo "Map not found"
-                            exit 1
-                        fi
-                        sleep 1
-                    done
+            ## Launch turtlebot simulation
+            TURTLEBOT3_MODEL=waffle_pi roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch &
+            pid=$!
+            echo "check simulation is running"
+            check_publishing scan 30
+            check_publishing joint_states 30
+            ## test core robot_state_publisher
+            check_existence rostopic tf 30
+            check_existence rosnode robot_state_publisher 300
+            ## test mapping node
+            sudo snap start turtlebot3c.mapping
+            check_existence rosnode turtlebot3_slam_gmapping 300
+            check_existence rostopic map 30
+            echo "moving the robot"
+            timeout 5s rostopic pub -r 10 /cmd_vel geometry_msgs/Twist -- '[0.0, 0.0, 0.0]' '[1.0, 0.0, 0.0]' || true
+            check_publishing map 30
+            sudo snap stop turtlebot3c.mapping
+            
+            ## check map has been created
+            timeout=300
+            start_time=$(date +%s)
+            while true; do
+                echo "check map exists.."
+                error_code=$(sudo bash -c 'cd /root/snap/turtlebot3c/common/map/ && ls | grep -q "current_map.yaml"'; echo $?)
+                if [ $error_code -eq 0 ]; then
+                  echo "map found - starting navigation"
+                  break
+                fi
+                current_time=$(date +%s)
+                elapsed_time=$((current_time - start_time))
+                if [ $elapsed_time -ge $timeout ]; then
+                    echo "Map not found"
+                    exit 1
+                fi
+                sleep 1
+            done
 
-                    ## test navigation node
-                    sudo snap start turtlebot3c.navigation
-                    check_existence rosnode move_base 30
-                    check_existence rostopic nav_vel 30
-                    sudo snap stop turtlebot3c.navigation
+            ## test navigation node
+            sudo snap start turtlebot3c.navigation
+            check_existence rosnode move_base 300
+            check_existence rostopic nav_vel 30
+            sudo snap stop turtlebot3c.navigation
 
-                    kill $pid
-                    sudo snap stop turtlebot3c
+            kill $pid
+            sudo snap stop turtlebot3c
+            
