add timeout and while loop to reduce flakyness

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -45,15 +45,27 @@ jobs:
                     check_existence() {
                         local topic_or_node=$1
                         local name=$2
-                        $1 list | grep -q "/$name"
-                        if [ $? -eq 0 ]; then
-                            echo "$name is running."
-                        else
-                            echo "Error $name is not running."
-                            sudo snap stop turtlebot3c
-                            killall -9 rosmaster
-                            exit 1
-                        fi
+                        local timeout=$3
+                        local start_time=$(date +%s)
+
+                        while true; do
+                            $topic_or_node list | grep -q "/$name"
+                            if [ $? -eq 0 ]; then
+                                echo "$name is running."
+                                return 0
+                            fi
+
+                            local current_time=$(date +%s)
+                            local elapsed_time=$((current_time - start_time))
+
+                            if [ $elapsed_time -ge $timeout ]; then
+                                echo "Error $name is not running."
+                                sudo snap stop turtlebot3c
+                                killall -9 rosmaster
+                                exit 1
+                            fi
+                            sleep 1
+                        done
                     }
 
                     ## test core robot_state_publisher
@@ -61,16 +73,13 @@ jobs:
 
                     ## test mapping node
                     sudo snap start turtlebot3c.mapping
-                    sleep 5
-                    check_existence rosnode turtlebot3_slam_gmapping
-                    check_existence rostopic map
+                    check_existence rosnode turtlebot3_slam_gmapping 10
+                    check_existence rostopic map 10
                     sudo snap stop turtlebot3c.mapping
 
                     ## test navigation node
                     sudo snap start turtlebot3c.navigation
-                    sleep 5
-                    check_existence rosnode move_base
-                    check_existence rostopic nav_vel
+                    check_existence rostopic nav_vel 10
                     sudo snap stop turtlebot3c.navigation
 
                     kill $pid
