add humble jazzy multi snap monthly check (#57)
* add humble jazzy multi snap monthly check

* add function to deal with -e test_script run

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -32,23 +32,26 @@ jobs:
                         local timeout=$2
                         local start_time=$(date +%s)
 
-                        while [ -z "${topic_data}" ]; do
-                          echo "waiting for /$name data"
-                          topic_data=$(rostopic echo -n 10 /$name 2>/dev/null)
-                          if [ -z "${topic_data}" ]; then
-                            echo "Topic /$name is not publishing data."
-                          else
-                            echo "Topic /$name is publishing data. Exiting."
-                          fi
+                        function is_publishing() {
+                          local name=$1
+                          rostopic echo /$name -n 10 > /dev/null 2>&1
+                          return $?
+                        }
 
-                          local current_time=$(date +%s)
-                          local elapsed_time=$((current_time - start_time))
-                          
-                          if [ $elapsed_time -ge $timeout ]; then
-                              echo "Error $name is not running."
-                              exit 1
-                          fi
-                          sleep 1
+                        while true; do
+                            if is_publishing ${name} ; then
+                                echo "Topic /$name is publishing data. Exiting."
+                                return 0
+                            fi
+
+                            local current_time=$(date +%s)
+                            local elapsed_time=$((current_time - start_time))
+
+                            if [ $elapsed_time -ge $timeout ]; then
+                                echo "Error $name is not publishing."
+                                exit 1
+                            fi
+                            sleep 1
                         done
                     }
 
@@ -58,9 +61,15 @@ jobs:
                         local timeout=$3
                         local start_time=$(date +%s)
 
+                        function is_running {
+                          local topic_or_node="${1}"
+                          local name="${2}"
+                          ($topic_or_node list | grep -q "/$name")
+                          return $?
+                        }
+
                         while true; do
-                            $topic_or_node list | grep -q "/$name"
-                            if [ $? -eq 0 ]; then
+                            if is_running "${topic_or_node}" "${name}" ; then
                                 echo "$name is running."
                                 return 0
                             fi
@@ -112,7 +121,7 @@ jobs:
                     check_existence rosnode turtlebot3_slam_gmapping 30
                     check_existence rostopic map 30
                     echo "moving the robot"
-                    timeout 5s rostopic pub -r 10 /cmd_vel geometry_msgs/Twist -- '[0.0, 0.0, 0.0]' '[1.0, 0.0, 0.0]'
+                    timeout 5s rostopic pub -r 10 /cmd_vel geometry_msgs/Twist -- '[0.0, 0.0, 0.0]' '[1.0, 0.0, 0.0]' || true
                     check_publishing map 30
                     sudo snap stop turtlebot3c.mapping
                     
