test only gazebo sim

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -28,23 +28,23 @@ jobs:
                     sudo apt update
                     sudo apt install ros-noetic-desktop-full
                     sudo apt install ros-noetic-turtlebot3-gazebo
-                    
+
                     source /opt/ros/noetic/setup.sh
 
                     ## Launch turtlebot simulation
-                    TURTLEBOT3_MODEL=waffle_pi roslaunch turtlebot3_gazebo turtlebot3_world.launch headless:=true &
-                    pid=$!
-                    sleep 20
+                    TURTLEBOT3_MODEL=waffle_pi roslaunch turtlebot3_gazebo turtlebot3_world.launch headless:=true
+                    # pid=$!
+                    # sleep 20
 
-                    snap info turtlebot3c
-                    sudo snap set turtlebot3c simulation=true
-                    
-                    rosnode list | grep -q "/robot_state_publisher"
-                    if [ $? -eq 0 ]; then
-                        echo "/robot_state_publisher" is running."
-                    else
-                        echo "Error - /robot_state_publisher is not running."
-                        exit 1
-                    fi
+                    # snap info turtlebot3c
+                    # sudo snap set turtlebot3c simulation=true
 
-                    kill $pid
+                    # rosnode list | grep -q "/robot_state_publisher"
+                    # if [ $? -eq 0 ]; then
+                    #     echo "/robot_state_publisher" is running."
+                    # else
+                    #     echo "Error - /robot_state_publisher is not running."
+                    #     exit 1
+                    # fi
+
+                    # kill $pid
