add timeout to check_publishing to avoid infinite jobs

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -22,6 +22,9 @@ jobs:
 
                     check_publishing() {
                         local name=$1
+                        local timeout=$2
+                        local start_time=$(date +%s)
+
                         while [ -z "${topic_data}" ]; do
                           echo "waiting for /$name data"
                           topic_data=$(rostopic echo -n 10 /$name 2>/dev/null)
@@ -29,7 +32,14 @@ jobs:
                             echo "Topic /$name is not publishing data."
                           else
                             echo "Topic /$name is publishing data. Exiting."
-                            echo "$topic_data"
+                          fi
+
+                          local current_time=$(date +%s)
+                          local elapsed_time=$((current_time - start_time))
+                          
+                          if [ $elapsed_time -ge $timeout_seconds ]; then
+                              echo "Error $name is not running."
+                              exit 1
                           fi
                           sleep 1
                         done
@@ -83,8 +93,8 @@ jobs:
                     pid=$!
 
                     echo "check simulation is running"
-                    check_publishing scan
-                    check_publishing joint_states
+                    check_publishing scan 30
+                    check_publishing joint_states 30
 
                     ## test core robot_state_publisher
                     check_existence rostopic tf 30
@@ -96,7 +106,7 @@ jobs:
                     check_existence rostopic map 30
                     echo "moving the robot"
                     timeout 5s rostopic pub -r 10 /cmd_vel geometry_msgs/Twist -- '[0.0, 0.0, 0.0]' '[1.0, 0.0, 0.0]'
-                    check_publishing map
+                    check_publishing map 30
                     sudo snap stop turtlebot3c.mapping
                     
                     ## check map has been created
