Feature/multi snap add ci tests (#27)
* add monthly build

* make workflow callable

* add hooks to enable core service once is connected to the foundational snap

* use reusable workflow to build the multiple snaps

* add test

* iterate through all folders in artifacts

* Update snap.yaml

* first install ros and launch sim then deal with snaps

* remove unused script

* conform with monolithic test

* add wait until connection is done and add debug

* add simulation

* debug connection

* use sudo when setting simulation

* add logs mapping

* debug

* fix

* sleep after starting mapping

* add debug

* pipe output to file

* add sleep

* publish once and check preserve status

* only once

* remove wrong command

* remove set -x

* run as bash

* fix

* add timeout to check publishing to avoid infinte jobs

* fix wrong variable

* use main branch

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -13,40 +13,184 @@ on:
 jobs:
 
   # Collect all relative paths containing a 'snap/snapcraft.yaml'
-  collect_dirs:
+  collect_snap_names:
     runs-on: ubuntu-latest
     outputs:
-      dirs: ${{ steps.dirs.outputs.dirs }}
+      snap-names: ${{ steps.snap-names.outputs.snap-names }}
     steps:
       - uses: actions/checkout@v3
-      - id: dirs
-        run: echo "dirs=$(find . -type f -name 'snapcraft.yaml' | sed -r 's|\/snap/[^/]+$||' |sort |uniq |jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
+      - id: snap-names
+        run: echo "snap-names=$(find . -type f -name 'snapcraft.yaml' | sed -r 's|^\./([^/]+)/snap/snapcraft.yaml|\1|' | sed 's/-snap$//' | sort | uniq | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
 
   # Run snapcraft for each example
-  run_tests:
-    needs: collect_dirs
-    runs-on: ubuntu-latest
+  build_snaps:
+    needs: collect_snap_names
     strategy:
       fail-fast: false
       matrix:
-        dir: ${{ fromJson(needs.collect_dirs.outputs.dirs) }}
-    name: "Snap ${{ matrix.dir }}"
+        snap-name: ${{ fromJson(needs.collect_snap_names.outputs.snap-names) }}
+    name: "Snap ${{ matrix.snap-name }}"
+    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@main
+    with:
+      branch-name: feature/multi-snap
+      snap-name: ${{ matrix.snap-name }}
+      snapcraft-build-path: ./${{ matrix.snap-name }}-snap
+      snap-install-args: --dangerous
+      snapcraft-args: --enable-experimental-extensions
+
+  test_snaps:
+    runs-on: ubuntu-20.04
+    needs: build_snaps
     steps:
-      - uses: actions/checkout@v3
-      - uses: snapcore/action-build@v1
-        id: build-snap
+      - uses: actions/download-artifact@v3
         with:
-          # Select the example we want to build
-          path: "${{ matrix.dir }}"
-          snapcraft-channel: 'latest/candidate'
-          snapcraft-args: '--enable-experimental-extensions'
+          path: .
+      - name: test-script
+        shell: bash
+        run: |
+            cat << 'EOF' > test-script.sh
+            #!/bin/bash
 
-      # Make sure the snap is installable
-      - run: sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}
+            check_publishing() {
+                local name=$1
+                local timeout=$2
+                local start_time=$(date +%s)
 
-      - uses: actions/upload-artifact@v3
-        continue-on-error: true
-        with:
-          name: snaps
-          path: ${{ steps.build-snap.outputs.snap }}
-          retention-days: 7
+                while [ -z "${topic_data}" ]; do
+                  echo "waiting for /$name data"
+                  topic_data=$(rostopic echo -n 10 /$name 2>/dev/null)
+                  if [ -z "${topic_data}" ]; then
+                    echo "Topic /$name is not publishing data."
+                  else
+                    echo "Topic /$name is publishing data. Exiting."
+                  fi
+
+                  local current_time=$(date +%s)
+                  local elapsed_time=$((current_time - start_time))
+                  
+                  if [ $elapsed_time -ge $timeout ]; then
+                      echo "Error $name is not running."
+                      exit 1
+                  fi
+                  sleep 1
+                done
+            }
+
+
+            check_existence() {
+                local topic_or_node=$1
+                local name=$2
+                local timeout=$3
+                local start_time=$(date +%s)
+
+                while true; do
+                    $topic_or_node list | grep -q "/$name"
+                    if [ $? -eq 0 ]; then
+                        echo "$name is running."
+                        return 0
+                    fi
+
+                    local current_time=$(date +%s)
+                    local elapsed_time=$((current_time - start_time))
+
+                    if [ $elapsed_time -ge $timeout ]; then
+                        echo "Error $name is not running."
+                        sudo snap stop turtlebot3c-bringup
+                        exit 1
+                    fi
+                    sleep 1
+                done
+            }
+
+            ## Install ROS
+            echo "Installing ROS"
+            sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
+
+            sudo apt install curl
+            curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
+            sudo apt -q update
+            sudo apt install -q ros-noetic-desktop-full
+            sudo apt install -q ros-noetic-turtlebot3-gazebo
+
+            source /opt/ros/noetic/setup.sh
+
+            echo "installing snaps"
+            # # Iterate through each file in the folder
+            for dir in */; do
+                cd "$dir" || exit
+                for file in *; do
+                    # Check if it is a regular file
+                    if [ -f "$file" ]; then
+                        sudo snap install "$file" --dangerous
+                    fi
+                done
+                cd ..
+            done
+
+            echo "Connect snaps to foundational snap"
+            sudo snap connect turtlebot3c-bringup:ros-noetic ros-noetic-robot
+            sudo snap connect turtlebot3c-nav:ros-noetic ros-noetic-robot
+            sudo snap connect turtlebot3c-teleop:ros-noetic ros-noetic-robot
+            sleep 10
+
+            echo "Set the simulation parameter"
+            sudo snap set turtlebot3c-bringup simulation=true
+            sudo snap set turtlebot3c-nav simulation=true
+            sleep 10
+
+            sudo snap start turtlebot3c-teleop.core
+            check_existence rosnode mux 30
+
+            ## set gui arg to false with sed since the arg is not exposed
+            sudo sed -i "s/\(<arg name=\"gui\" value=\"\).*\(\"\/>\)/\1false\2/" /opt/ros/noetic/share/turtlebot3_gazebo/launch/turtlebot3_empty_world.launch
+
+            ## Launch turtlebot simulation
+            TURTLEBOT3_MODEL=waffle_pi roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch debug:=true &
+            pid=$!
+
+            echo "check simulation is running"
+            check_publishing scan 30
+            check_publishing joint_states 30
+
+            ## test core robot_state_publisher
+            check_existence rostopic tf 30
+            check_existence rosnode robot_state_publisher 30
+
+            ## test mapping node
+            sudo snap start turtlebot3c-nav.mapping
+            check_existence rostopic map 30
+            check_existence rosnode turtlebot3_slam_gmapping 30
+            echo "moving the robot"
+            timeout 10s rostopic pub -r 10 /cmd_vel geometry_msgs/Twist -- '[0.0, 0.0, 0.0]' '[1.0, 0.0, 0.0]'
+            sudo snap stop turtlebot3c-nav.mapping
+
+            ## check map has been created
+            timeout=30
+            start_time=$(date +%s)
+            while true; do
+              echo "check map exists.."
+              sudo bash -c 'cd /root/snap/turtlebot3c-nav/common/map/ && ls | grep -q ".yaml"'
+              if [ $? -eq 0 ]; then
+                echo "map found - starting navigation"
+                break
+              fi
+              current_time=$(date +%s)
+              elapsed_time=$((current_time - start_time))
+              if [ $elapsed_time -ge $timeout ]; then
+                echo "Map not found"
+                exit 1
+              fi
+              sleep 1
+            done
+
+            sudo snap start turtlebot3c-nav.navigation
+            check_existence rosnode move_base 30
+            check_existence rostopic nav_vel 30
+            sudo snap stop turtlebot3c-nav.navigation
+
+            kill $pid
+            sudo snap stop turtlebot3c-bringup
+
+            EOF
+
+            bash test-script.sh
