fix(firmware): test on UC server

diff --git a/snap/hooks/post-refresh b/snap/hooks/post-refresh
--- a/snap/hooks/post-refresh
+++ b/snap/hooks/post-refresh
@@ -1,16 +1,17 @@
 #!/bin/sh
 
-auto-update=$(snapctl get opencr-auto-update)
-if [[ "$auto-update" == "false" ]]; then
-  logger -t "$SNAP_NAME" "OpenCR auto update is disabled. Skipping the update."
+logger -t $SNAP_NAME "Post refresh hook starting."
+
+auto_update=$(snapctl get opencr-auto-update)
+if [ "$auto_update" = "false" ]; then
+  logger -t $SNAP_NAME "OpenCR auto update is disabled. Skipping the update."
   exit 0
 fi
 
-output=$($SNAP/bin/update_firmware.sh 2>&1)
-if [[ $? -eq 0 ]]; then
-  logger -t "$SNAP_NAME" "OpenCR auto update succeeded: $output"
-  snapctl set-health okay
+output=$($SNAP/usr/bin/update_firmware.sh 2>&1)
+if [ $? -eq 0 ]; then
+  logger -t $SNAP_NAME "OpenCR auto update succeeded: $output"
 else
-  snapctl set-health error "OpenCR auto update failed: $output"
+  logger -t $SNAP_NAME "OpenCR auto update failed: $output"
 fi
 
